### ISSUE TITLE
get_td_waveform 中的 SEOBNREHM

### ISSUE THREAD

**Issue by Doubleking-1** [yi-fan-wang/Gwaveform-tools#1]
你好，我想问一个问题：
pycbc中的get_td_waveform好像没有SEOBNREHM吧
在example.ipynb中怎么去画的SEOBNREHM波形

**Comment by yi-fan-wang** [comment]
@Doubleking-1 你好：

调用SEOBNREHM波形需要先安装它，可参考http://pycbc.org/pycbc/latest/html/waveform_plugin.html, SEOBNREHM的波形代码在https://github.com/Shallyn/pyWaveformGenerator
